# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nabil/mp1_c/mp1_c.srcs/sources_1/bd/system_c/ip/system_c_rst_ps7_0_100M_0/system_c_rst_ps7_0_100M_0.xci
# IP: The module: 'system_c_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nabil/mp1_c/mp1_c.gen/sources_1/bd/system_c/ip/system_c_rst_ps7_0_100M_0/system_c_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_c_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nabil/mp1_c/mp1_c.gen/sources_1/bd/system_c/ip/system_c_rst_ps7_0_100M_0/system_c_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_c_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/nabil/mp1_c/mp1_c.srcs/sources_1/bd/system_c/ip/system_c_rst_ps7_0_100M_0/system_c_rst_ps7_0_100M_0.xci
# IP: The module: 'system_c_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nabil/mp1_c/mp1_c.gen/sources_1/bd/system_c/ip/system_c_rst_ps7_0_100M_0/system_c_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_c_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nabil/mp1_c/mp1_c.gen/sources_1/bd/system_c/ip/system_c_rst_ps7_0_100M_0/system_c_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_c_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
