# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_xbar_0/system_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==system_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_pc_3/system_axi_mem_intercon_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_pc_3 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_pc_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_3/system_axi_mem_intercon_imp_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_3 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_pc_4/system_axi_mem_intercon_imp_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_pc_4 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_pc_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_4/system_axi_mem_intercon_imp_auto_us_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_4 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_pc_5/system_axi_mem_intercon_imp_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_pc_5 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_pc_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_imp_auto_us_5/system_axi_mem_intercon_imp_auto_us_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_imp_auto_us_5 || ORIG_REF_NAME==system_axi_mem_intercon_imp_auto_us_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/system/ip/system_caesar_cipher_accele_0_0/system_caesar_cipher_accele_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_caesar_cipher_accele_0_0 || ORIG_REF_NAME==system_caesar_cipher_accele_0_0} -quiet] -quiet

# XDC: c:/Users/nabil/mp1_partd/mp1_partd.gen/sources_1/bd/system/system_ooc.xdc
