# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_c/system_c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c || ORIG_REF_NAME==system_c} -quiet] -quiet

# IP: bd/system_c/ip/system_c_processing_system7_0_0/system_c_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_processing_system7_0_0 || ORIG_REF_NAME==system_c_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_c/ip/system_c_axi_gpio_0_0/system_c_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_axi_gpio_0_0 || ORIG_REF_NAME==system_c_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system_c/ip/system_c_axi_smc_0/system_c_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_axi_smc_0 || ORIG_REF_NAME==system_c_axi_smc_0} -quiet] -quiet

# IP: bd/system_c/ip/system_c_rst_ps7_0_100M_0/system_c_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_c_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_c_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/nabil/mp1_c/mp1_c.gen/sources_1/bd/system_c/system_c_ooc.xdc
