set_property SRC_FILE_INFO {cfile:c:/Users/qyliu/mp1_partd/mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_sarn_0_ooc.xdc rfile:../../../mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_sarn_0_ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/qyliu/mp1_partd/mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_srn_0_ooc.xdc rfile:../../../mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_srn_0_ooc.xdc id:2 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/qyliu/mp1_partd/mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_sawn_0_ooc.xdc rfile:../../../mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_sawn_0_ooc.xdc id:3 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/qyliu/mp1_partd/mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_swn_0_ooc.xdc rfile:../../../mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_swn_0_ooc.xdc id:4 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/qyliu/mp1_partd/mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_sbn_0_ooc.xdc rfile:../../../mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/bd_44e3_sbn_0_ooc.xdc id:5 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/qyliu/mp1_partd/mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/ooc.xdc rfile:../../../mp1_partd.gen/sources_1/bd/system/ip/system_caesar_cipher_accele_0_0/src/ooc.xdc id:6 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 100.0 -name s_sc_aclk [get_ports s_sc_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 100.0 -name s_sc_aclk [get_ports s_sc_aclk]
set_property src_info {type:SCOPED_XDC file:3 line:50 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 100.0 -name s_sc_aclk [get_ports s_sc_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:50 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 100.0 -name s_sc_aclk [get_ports s_sc_aclk]
set_property src_info {type:SCOPED_XDC file:5 line:50 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 100.0 -name s_sc_aclk [get_ports s_sc_aclk]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -name aclk -period 10.000 [get_ports aclk]
